"""audit fields

Revision ID: 47753905f670
Revises: b42013a19db8
Create Date: 2019-10-08 16:20:55.863059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47753905f670'
down_revision = 'b42013a19db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('post', 'updated_on')
    op.drop_column('post', 'created_on')
    # ### end Alembic commands ###
